apiVersion: v2
name: devops-api
description: Pequena API Flask usada para o laboratório de DevOps
type: application
version: 0.1.0        # versão do chart (muda quando os templates mudam)
appVersion: "local"   # versão da aplicação empacotada