namespace: devops-lab

replicaCount: 2

image:
  repository: ghcr.io/muriloalmeida123/devops-api
  tag: 78ee365
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

containerPort: 5000